# Generated by Django 3.2.9 on 2022-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmanagement',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
