# Generated by Django 3.2.9 on 2022-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_alter_taskmanagement_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanagement',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
