# Generated by Django 3.2.9 on 2022-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_taskmanagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanagement',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmanagement',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
